"""Add sharing fields

Revision ID: 7e636c3d5d0d
Revises: 6c88151eeac3
Create Date: 2026-03-25 20:35:37.688414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e636c3d5d0d'
down_revision: Union[str, None] = '6c88151eeac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('projects', sa.Column('public_access_level', sa.String(), server_default='view', nullable=True))
    
    # Update existing rows
    op.execute("UPDATE projects SET is_public = false WHERE is_public IS NULL")
    op.execute("UPDATE projects SET public_access_level = 'view' WHERE public_access_level IS NULL")
    
    # Now make them non-nullable if desired, or just leave as is. 
    # For now, just ensuring they have values is enough to satisfy Pydantic.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'public_access_level')
    op.drop_column('projects', 'is_public')
    # ### end Alembic commands ###
