name: Deploy to Selectel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/web-graph || { git clone https://github.com/${{ github.repository }} ~/web-graph && cd ~/web-graph; }
            
            git pull origin main
            
            # 1. Останавливаем старые контейнеры
            docker-compose down
            
            # 2. Запускаем новые (флаг -v при желании очистит старые данные, если нужно)
            docker-compose up -d --build
            
            # 3. КРИТИЧЕСКИЙ ШАГ: Ждем, пока база станет "Healthy"
            echo "Waiting for database to be ready..."
            for i in {1..20}; do
              if [ "$(docker inspect --format='{{.State.Health.Status}}' $(docker-compose ps -q db))" == "healthy" ]; then
                echo "Database is up and running!"
                break
              fi
              echo "Waiting... ($i/20)"
              sleep 2
            done

            # 4. Только теперь запускаем миграции
            docker-compose exec -T web alembic upgrade head
